// import {add function name in here} from "./main.js";

// THINGS TO TEST:
// DOES IT SUCCESSFULLY TRANSLATE A CHARACTER
// DOES IT SUCCESSFULLY TRANSLATE A WORD
// DOES IT SUCCESSFULLY TRANSLATE A SENTENCE
// CAN IT HANDLE PUNCTUATION?
// SOMETHING TO HANDLE INVALID INPUTS
// ETC. ANYTHING ELSE?


// DON'T FORGET .babelrc
// separate out the class?
